name: HirenPatel Build & Publish Debug APK

on:
 push:
  branches:
   - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Generate the Android App Bundle
      working-directory: ./platforms/android/
      run: ./gradlew bundle
    - name: Upload dev APK
      uses: actions/checkout@v2
      with:
          name: app-dev
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
    - name: Upload release bundle
      uses: actions/checkout@v2
      with:
          name: app-release
          path: platforms/android/app/build/outputs/bundle/release/app.aab
    env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
       RELEASE_TITLE: New Build
